### ISSUE TITLE
scispacy entity linker throwing error

### ISSUE THREAD

**Issue by ritika24-s** [allenai/scispacy#255]
[log_error.txt](https://github.com/allenai/scispacy/files/4959121/log_error.txt)
i am trying to deploy a code on docker where i am using scispacy's entity linker with mesh functionality. it's giving EOF error in watchlog.
using versions,
en-core-sci-lg 0.2.4
scispacy 0.2.5
spacy 2.2.1
the line throwing error:
linker = EntityLinker(resolve_abbreviations=True, name="mesh")

**Comment by VeereshShringari** [comment]
I am also facing same issue is there any solution for this ? my production code pass is held because of this

**Comment by danielkingai2** [comment]
Sorry, this is a version issue. scispacy 0.2.5 requires spacy 2.3.x and model version 0.2.5.

**Comment by ritika24-s** [comment]
Hi still an error throwing in even after updating en_core_sci_lg to 2.5, while creating Linker. Any clue on that? i have attached all my packages installed in the env.`
[env_pack.txt](https://github.com/allenai/scispacy/files/4965782/env_pack.txt)
`

**Comment by danielkingai2** [comment]
Your package list still shows `en-core-sci-lg` 0.2.4. you need to pip install the new model https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.2.5/en_core_sci_lg-0.2.5.tar.gz

**Comment by joeworrall** [comment]
I'm having the same error, too, but I have the correct versions installed (en-ner-bionlp13cg-md 0.2.5 + spacy 2.3.2 + scispacy 0.2.5). 

Throwing the following error:
`TypeError                                 Traceback (most recent call last)
<ipython-input-262-eadd79906c1b> in <module>
----> 1 linker = EntityLinker(resolve_abbreviations=True, name="mesh")

~\Anaconda3\lib\site-packages\scispacy\linking.py in __init__(self, candidate_generator, resolve_abbreviations, k, threshold, no_definition_threshold, filter_for_definitions, max_entities_per_mention, name)
     75         Span.set_extension("kb_ents", default=[], force=True)
     76 
---> 77         self.candidate_generator = candidate_generator or CandidateGenerator(name=name)
     78         self.resolve_abbreviations = resolve_abbreviations
     79         self.k = k

TypeError: __init__() got an unexpected keyword argument 'name'`

[installed conda packages.txt](https://github.com/allenai/scispacy/files/4968036/installed.conda.packages.txt)

**Comment by danielkingai2** [comment]
hmm, i am not able to reproduce this. Could you try it in a clean environment?

**Comment by joeworrall** [comment]
Clean environment solved it, thanks for the help!
